config/routes.rb
Rails.application.routes.draw do
  resources :maquinas
  root "maquinas#index"
  
  get "/maquinas", to:"maquinas#index"
  get "/maquinas/:id", to: "maquinas#show"
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/maquina.rb
class Maquina < ApplicationRecord
	validates :nome, length: {in: 2..80}
	validates :descricao, length: {maximum: 1000}
	validates :mesesdegarantia, numericality: {only_integer: true}
	validate :datadecomprapassado
	
	def datadecomprapassado
		datadecompra.strftime("%m/%d/%Y")
		if datadecompra.present? && datadecompra>Date.today
			errors.add(:datadecompra, "Deve ser uma data no passado.")
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maquinas_controller.rb
class MaquinasController < ApplicationController
	def index
		@maquinas = Maquina.all
	end

	def new 
		@maquina = Maquina.new
	end
	
	def create
		@maquina = Maquina.new(maquina_params)
		
		if @maquina.save
			redirect_to @maquina
		else
			render :new
		end
	end
	
	def show
		@maquina = Maquina.find(params[:id])
		
		respond_to do |format|
			format.html 
			format.json { render :json => @maquina}
		end
	end
	
	def edit
		@maquina = Maquina.find(params[:id])
	end
	
	def update
		@maquina = Maquina.find(params[:id])
		
		if @maquina.update(maquina_params)
			redirect_to @maquina
		else
			render :edit
		end
	end
	
	def destroy
		@maquina = Maquina.find(params[:id])
		@maquina.destroy if @maquina.created_at > 30.minutes.ago
		
		redirect_to root_path
	end
	
	private
	
	def maquina_params
		params.require(:maquina).permit(:tipo, :nome, :descricao, :mesesdegarantia, :datadecompra, :quebrada, :created_at)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/maquinas_helper.rb
module MaquinasHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gerenciamento de Máquinas</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background: #EEEEEE;">
    <%= yield %>
  </body>
</html>

app/views/maquinas/_form.html.erb
<%= form_with model: maquina do |form| %>
	<div>
		<%= form.label :tipo, "Tipo: " %> <br>
		<%= form.text_field :tipo %>
		<% @maquina.errors.full_messages_for(:tipo).each do |message| %>
			<div>
				<%= message %>
			</div>
		<% end %>
	</div>
	
	<div>
		<%= form.label :nome, "Nome: " %> <br>
		<%= form.text_field :nome %>
		<% @maquina.errors.full_messages_for(:nome).each do |message| %>
			<div>
				<%= message %>
			</div>
		<% end %>
	</div>
	
	<div>
		<%= form.label :descricao, "Descrição: " %> <br>
		<%= form.text_area :descricao %>
		<% @maquina.errors.full_messages_for(:descricao).each do |message| %>
			<div>
				<%= message %>
			</div>
		<% end %>
	</div>
	
	<div>
		<%= form.label :mesesdegarantia, "Meses de Garantia: " %> <br>
		<%= form.text_field :mesesdegarantia %>
		<% @maquina.errors.full_messages_for(:mesesdegarantia).each do |message| %>
			<div>
				<%= message %>
			</div>
		<% end %>
	</div>
	
	<div>
		<%= form.label :datadecompra, "Data de Compra: " %> <br>
		<%= form.date_field :datadecompra %>
		<% @maquina.errors.full_messages_for(:datadecompra).each do |message| %>
			<div>
				<%= message %>
			</div>
		<% end %>
	</div>
	
	<div>
		<%= form.label :quebrada, "Quebrada:" %> <br>
		<%= form.radio_button(:quebrada, "true") %>
		<%= form.label(:quebrada_true, "Sim") %>
		<%= form.radio_button(:quebrada, "false") %>
		<%= form.label(:quebrada_true, "Não") %>
		<% @maquina.errors.full_messages_for(:quebrada).each do |message| %>
			<div>
				<%= message %>
			</div>
		<% end %>
	</div>
	
	<div>
		<%= form.submit "Salvar" %>
	</div>
	
<% end %>

app/views/maquinas/edit.html.erb
<h1> Modificar Máquina </h1>

<%= render "form", maquina: @maquina %>

<%= link_to "Mostrar Máquina", @maquina %> |
<%= link_to "Voltar", maquinas_path %>

app/views/maquinas/index.html.erb
<h1> Gerenciamento de Máquinas </h1>

<table>
	<tr>
		<th> Tipo </th>
		<th> Nome </th>
		<th> Descrição </th>
		<th> Meses de Garantia </th>
		<th> Data de Compra </th>
		<th> Quebrada </th>
	</tr>

<% @maquinas.each do |maquina| %>
	<tr>
		<td><%= maquina.tipo %></td>
		<td><%= maquina.nome %></td>
		<td><%= maquina.descricao %></td>
		<td><%= maquina.mesesdegarantia %></td>
		<td><%= maquina.datadecompra.strftime("%d/%m/%Y") %></td>
		<td><%= maquina.quebrada.to_yesno %></td>
		
		<td><%= link_to "Mostrar", maquina %></td>
		<td><%= link_to "Modificar", edit_maquina_path(maquina) %></td>
		<td><%= link_to "Apagar", maquina, confirm: "Tem certeza que quer excluir a Máquina?", method: :delete %></td>
	</tr>
<% end %>
</table

<br />

<%= link_to "Criar nova Máquina", new_maquina_path %>

app/views/maquinas/new.html.erb
<h1> Criar Máquina </h1>

<%= render "form", maquina: @maquina %>
	
<%= link_to "Voltar", maquinas_path %>

app/views/maquinas/show.html.erb
<p id="notice"> <%= notice %> </p>

<p>
	<b>Tipo: </b>
	<%= @maquina.tipo %>
</p>

<p>
	<b>Nome: </b>
	<%= @maquina.nome %>
</p>

<p>
	<b>Descrição: </b>
	<%= @maquina.descricao %>
</p>

<p>
	<b>Meses de Garantia: </b>
	<%= @maquina.mesesdegarantia %>
</p>

<p>
	<b>Data de Compra: </b>
	<%= @maquina.datadecompra.strftime("%d/%m/%Y") %>
</p>

<p>
	<b>Quebrada: </b>
	<%= @maquina.quebrada.to_yesno %>
</p>

<%= link_to "Modificar", edit_maquina_path(@maquina) %> |
<%= link_to "Voltar", maquinas_path %>